# conda env create --file environment.yml
# mamba env create --file environment.yml

name: data_analyst_

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - jupyter
  - plotly
  - pip
  - pip:
      - streamlit